
### CADASTRAR ANIMAL
POST http://localhost:5080/adopet/animais/cadastrar
Content-Type: application/json

{
    "nome": "Rex",
    "especie": "Cachorro",
    "raca": "Labrador",
    "idade": 5,
    "disponivelParaAdocao": true,
    "abrigoId": 1
}

### LISTAR ANIMAIS
GET http://localhost:5080/adopet/animais/listar
Accept: application/json

### EXCLUIR ANIMAL
DELETE http://localhost:5080/adopet/animais/24

